version: "3.9"

services:

  db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_DB: "manager_db"
      POSTGRES_USER: "manager"
      POSTGRES_PASSWORD: "asdfg1966"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  webapp:
#    restart: always
    build:
      context: ./webapp
    depends_on:
      - "db"
    ports:
      - "8000:8000"
    command: [ "python3", "./src/manage.py", "runserver", "0.0.0.0:8000" ]
    env_file:
      - ./.env.dev

  redis:
    image: redis
    restart: always

  worker:
    restart: always
    build:
      context: ./webapp
    env_file:
      - ./.env.dev
    depends_on:
      - "db"
      - "webapp"
    command: ['celery', '--workdir=./src', '-A', 'config', 'worker']

  celery-beats:
    restart: always
    build:
      context: ./webapp
    env_file:
      - ./.env.dev
    depends_on:
      - "db"
      - "webapp"
    command: ['celery', '--workdir=./src', '-A', 'config', 'beat', '-l', 'INFO', '--scheduler', 'django_celery_beat.schedulers:DatabaseScheduler']

volumes:
  postgres_data: