version: "3.9"

services:

  db:
    image: postgres:15.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
#    ports:
#      - "5432:5432"

  webapp:
#    restart: always
    build:
      context: ./webapp
      dockerfile: Dockerfile
    command: sh -c "cd ./src && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - "db"

  redis:
    image: redis
    restart: always

  worker:
    restart: always
    build:
      context: ./webapp
      dockerfile: Dockerfile.celery
    env_file:
      - ./.env.prod
    depends_on:
      - "webapp"
    command: ['celery', '--workdir=./src', '-A', 'config', 'worker']

  celery-beats:
    restart: always
    build:
      context: ./webapp
      dockerfile: Dockerfile.celery
    env_file:
      - ./.env.prod
    depends_on:
      - "webapp"
    command: ['celery', '--workdir=./src', '-A', 'config', 'beat', '-l', 'INFO', '--scheduler', 'django_celery_beat.schedulers:DatabaseScheduler']

volumes:
  postgres_data: